# Generated by Django 3.0.6 on 2020-05-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicines', '0003_auto_20200524_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.FileField(null=True, upload_to='upload/'),
        ),
    ]
